set_targetdir("./")
set_languages("cxx17")

set_toolchains("clang")
set_warnings("allextra", "error")
set_optimize("fastest")
set_symbols("debug")

add_requires("freetype")
add_requires("glfw")
add_requires("glm")
add_requires("stb")
add_requires("glad")
add_requires("box2d")
add_requires("nlohmann_json")
add_requires("imgui 993fa347495860ed44b83574254ef2a317d0c14f", {configs = {glfw = true, opengl3 = true}})
add_requires("magic_enum")
includes("submodules/Engine")

target("game")
    set_kind("binary")
    add_files("srcs/Game/**.cpp")
    add_includedirs("srcs")
    add_packages("glfw")
    add_packages("glm")
    add_packages("stb")
    add_packages("glad")
    add_packages("box2d")
    add_packages("nlohmann_json")
    add_deps("Engine")

target("editor")
    set_kind("binary")
    add_files("srcs/Editor/**.cpp")
    add_includedirs("srcs")
    add_packages("glfw")
    add_packages("glm")
    add_packages("stb")
    add_packages("glad")
    add_packages("box2d")
    add_packages("nlohmann_json")
    add_packages("imgui")
    add_packages("magic_enum")
    add_deps("Engine")